server:
    port: 9080

spring:
    application:
      name: demoservice
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/cloud_project?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: 123456
eureka:
  client:
    service-url:
        defaultZone: http://localhost:9099/eureka