# 开发环境配置
server:
    # 服务器的HTTP端口，默认为8080
    port: 8888

# Spring配置
spring:
    datasource:
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8
        driver-class-name: com.mysql.cj.jdbc.Driver

