# Tomcat
server:
    port: 9099

# Spring
spring:
    application:
        # 应用名称
        name: eureka-demo
eureka:
    client:
        sevice-url:
            defaultZone: http://localhost:${server.port}/eureka
        register-with-eureka: false
        fetch-registry: false


# MyBatis配置
# https://baomidou.com/config/
mybatis-plus:
    mapperLocations: classpath:mapper/**/*.Mapper.xml
    configuration:
        # 返回类型为Map,显示null对应的字段
        call-setters-on-nulls: true
        # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
